version: "2"
plugins:
  fixme:
    enabled: true
  duplication:
    enabled: true
checks:
  file-lines:
    config:
      threshold: 300
  method-lines:
    config:
      threshold: 30
  method-complexity:
    config:
      threshold: 7
  similar-code:
    enabled: false
  identical-code:
    enabled: false
exclude_patterns:
  - 'Gruntfile.js'
  - '**/*conf.js'
  - 'data/datacreator.ts'
  - 'data/static/codefixes/**'
  - 'frontend/src/hacking-instructor/**/*.ts'
  - 'frontend/src/assets/private/*.js'
  - 'lib/logger.ts'
  - 'lib/config.types.ts'
