services:
  sut:
    build: ./test/smoke/
    links:
      - app
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - seccomp:unconfined
  app:
    image: bkimminich/juice-shop:latest
    build: ./
