# OWASP Juice Shop - An intentionally insecure JavaScript Web Application
FROM            arm32v7/node:6
MAINTAINER      Bjoern Kimminich <bjoern.kimminich@owasp.org>
LABEL version = "5.1.0-SNAPSHOT"

COPY . /juice-shop
WORKDIR /juice-shop
RUN npm install --production --unsafe-perm

EXPOSE  3000
CMD ["npm", "start"]
