42:       properties: { productId: { type: integer, example: 8, format: 'int32', maximum: 1000 }, quantity: { type: integer, example: 500, minimum: 1, maximum: 1000, maxLength: 10, pattern: '^[0-9]+$' }, customerReference: { type: string, example: 'PO0000001', pattern: '^[A-Z0-9-]*$', maxLength: 20 } }  
43:     OrderLines:  
43:       type: array, maxItems: 100  
48:       type: string, pattern: '^[a-zA-Z0-9\[\]\.\-]*$', maxLength: 255  
52:     bearerAuth: ['Bearer Token']  
