# Copyright (c) 2014-2021 Bjoern Kimminich.
# SPDX-License-Identifier: MIT

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "juice.sh"

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "file", source: "./default.conf", destination: "/tmp/juice-shop/default.conf"
  config.vm.provision :shell, path: "bootstrap.sh"
end
