# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "juice.sh"

  config.vm.provision "shell", inline: "sudo mkdir -p /var/www/html && chmod 777 /var/www/html" 
  config.vm.provision "shell", inline: "sudo mkdir -p /etc/apache2/sites-enabled/ && chmod 777 /etc/apache2/sites-enabled/" 

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "file", source: "./logger.php", destination: "/var/www/html/logger.php"
  config.vm.provision "file", source: "./shake.js", destination: "/var/www/html/shake.js"
  config.vm.provision "file", source: "./default.conf", destination: "/etc/apache2/sites-enabled/000-default.conf"

  config.vm.provision :shell, path: "bootstrap.sh"

end
