# OWASP Juice Shop - An intentionally insecure JavaScript Web Application
FROM            node:%%NODE_VERSION%%-alpine
MAINTAINER      Bjoern Kimminich <bjoern.kimminich@owasp.org>
LABEL version = "%%APP_VERSION%%"

RUN apk update && apk add git

COPY . /juice-shop
WORKDIR /juice-shop
RUN npm install --production --unsafe-perm

EXPOSE  3000
CMD ["npm", "start"]
