# OWASP Juice Shop - An intentionally insecure JavaScript Web Application
FROM            arm32v7/node:%%NODE_VERSION%%
MAINTAINER      Bjoern Kimminich <bjoern.kimminich@owasp.org>
LABEL version = "%%APP_VERSION%%"

COPY . /juice-shop
WORKDIR /juice-shop
RUN npm install --production --unsafe-perm

EXPOSE  3000
CMD ["npm", "start"]
