name: Build & Push to DockerHub

on:
  push:
    branches: [main]  # change if you're using another branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/juice-shop:latest .

    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/juice-shop:latest
