export const languages = [
    { key: 'en', icons: [ 'gb', 'us' ], lang: 'English' },
    { key: 'ar_SA', icons: [ 'ae', 'tn' ], lang: 'عربى' },
    { key: 'cs_CZ', icons: [ 'cz' ], lang: 'Česky', isFlask: true },
    { key: 'da_DK', icons: [ 'dk' ], lang: 'Dansk', isFlask: true },
    { key: 'de_DE', icons: [ 'de' ], lang: 'Deutsch' },
    { key: 'el_GR', icons: [ 'gr' ], lang: 'Ελληνικά', isFlask: true },
    { key: 'es_ES', icons: [ 'es' ], lang: 'Español', isFlask: true },
    { key: 'et_EE', icons: [ 'ee' ], lang: 'Eesti' },
    { key: 'fi_FI', icons: [ 'fi' ], lang: 'Suomalainen', isFlask: true },
    { key: 'fr_FR', icons: [ 'fr' ], lang: 'Français' },
    { key: 'he_IL', icons: [ 'il' ], lang: 'עברי', isFlask: true },
    { key: 'hi_IN', icons: [ 'in' ], lang: 'हिंदी' },
    { key: 'hu_HU', icons: [ 'hu' ], lang: 'Magyar', isFlask: true },
    { key: 'id_ID', icons: [ 'id' ], lang: 'Bahasa Indonesia' },
    { key: 'it_IT', icons: [ 'it' ], lang: 'Italiano' },
    { key: 'ja_JP', icons: [ 'jp' ], lang: '日本の', isFlask: true },
    { key: 'lt_LT', icons: [ 'lt' ], lang: 'Lietuviešu', isFlask: true },
    { key: 'lv_LV', icons: [ 'lv' ], lang: 'Latvijas', isFlask: true },
    { key: 'my_MM', icons: [ 'mm' ], lang: 'ျမန္မာ', isFlask: true },
    { key: 'nl_NL', icons: [ 'nl' ], lang: 'Nederlands' },
    { key: 'no_NO', icons: [ 'no' ], lang: 'Norsk', isFlask: true },
    { key: 'pl_PL', icons: [ 'pl' ], lang: 'Język Polski' },
    { key: 'pt_PT', icons: [ 'pt' ], lang: 'Português', isFlask: true },
    { key: 'pt_BR', icons: [ 'br' ], lang: 'Português (Brasil)' },
    { key: 'ro_RO', icons: [ 'ro' ], lang: 'Românesc', isFlask: true },
    { key: 'ru_RU', icons: [ 'ru' ], lang: 'Pусский', isFlask: true },
    { key: 'sv_SE', icons: [ 'se' ], lang: 'Svenska' },
    { key: 'tr_TR', icons: [ 'tr' ], lang: 'Türkçe', isFlask: true },
    { key: 'ur_PK', icons: [ 'pk' ], lang: 'اردو', isFlask: true },
    { key: 'zh_CN', icons: [ 'cn' ], lang: '中国' },
    { key: 'zh_HK', icons: [ 'hk' ], lang: '繁體中文', isFlask: true }
]
