pipeline:
  name: original scan harness
  identifier: original_scan_harness
  tags: {}
  projectIdentifier: juiceShop_bm
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: final_js_bm
        build: <+input>
  stages:
    - stage:
        name: init
        identifier: init
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.remediationagentdelegate
              namespace: harness-qa-delegate
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep_1
                  identifier: Semgrep_1
                  spec:
                    target:
                      detection: auto
                      type: repository
                    advanced:
                      log:
                        level: info
                      args: {}
                    mode: orchestration
                    config: default
              - parallel:
                  - step:
                      type: Owasp
                      name: Owasp_1
                      identifier: Owasp_1
                      spec:
                        target:
                          detection: auto
                          type: repository
                        advanced:
                          log:
                            level: info
                          args:
                            passthrough: --exclude /harness/test/files
                        mode: orchestration
                        config: default
                  - step:
                      type: OsvScanner
                      name: OsvScanner_1
                      identifier: OsvScanner_1
                      spec:
                        target:
                          detection: auto
                          type: repository
                        advanced:
                          log:
                            level: info
                          args: {}
                        mode: orchestration
                        config: default
              - step:
                  type: Gitleaks
                  name: Gitleaks_1
                  identifier: Gitleaks_1
                  spec:
                    target:
                      detection: auto
                      type: repository
                    advanced:
                      log:
                        level: info
                      args: {}
                    mode: orchestration
                    config: default
