name: "DevSecOps Pipeline"
on:
  pull_request:
    branches: [master]
  push: 
    branches: [master]
    
jobs:
  Trufflehog: 
   name: Trufflehog
   runs-on: ubuntu-20.04
   container:
      image: trufflesecurity/trufflehog
   steps:
    - name: TruffleHog OSS
      uses: actions/checkout@v3
    - run: trufflehog github --repo https://github.com/undeadjie/juice-shop 
    
  OSV-Scanner: 
   name: OSV-Scanner
   runs-on: ubuntu-20.04
   steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: npm install
      uses: actions/setup-node@v3
      with:
       node-version: 16
    - run: npm install --package-lock
    - name: Software Composition Analysis
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker run --rm -v $(pwd):/home sharaking/osv-scanner --json --lockfile=/home/package-lock.json 

  semgrep:
   name: semgrep/ci
   runs-on: ubuntu-20.04
   env:
    SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
   container:
     image: returntocorp/semgrep
   steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Semgrep
      run: export result = $(semgrep ci)
    - name: Add comment to PR
      uses: actions/github-script@v6
      with:
        script: |
          const name = '${{ github.workflow   }}';
          const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
          const success = '${{ job.status }}' === 'success';
          const body = `${name}: ${result} ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          })
      
  docker:
    name: docker/ci
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build . -t sharaking/juice-shop:v1
      - name: Docker Push
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push sharaking/juice-shop:v1
