name: "DevSecOps Pipeline"
on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]
    
jobs:
  Trufflehog: 
   name: Trufflehog
   runs-on: ubuntu-20.04
   container:
      image: trufflesecurity/trufflehog
   steps:
    - name: TruffleHog OSS
      uses: actions/checkout@v3
    - run: trufflehog github --repo https://github.com/undeadjie/juice-shop 

  semgrep:
   name: semgrep/ci
   needs: OSV-Scanner
   runs-on: ubuntu-20.04
   env:
    SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
   container:
     image: returntocorp/semgrep
   if: (github.actor != 'dependabot[bot]')
   steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
      
  docker:
    name: docker/ci
    needs: semgrep
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build . -t sharaking/juice-shop:v1
      - name: Docker Push
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push sharaking/juice-shop:v1
