# This is a basic workflow to help you get started with Actions

name: Hello World

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello-world-ubuntu:
    name: Hello World Ubuntu
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  hello-world-windows:
    name: Hello World Windows
    runs-on: windows-latest
    
    steps:
      - name: Print Hello world Windows
        run: echo 'Hello world rodando no windows'
        
  hello-world-macos:
    name: Hello Wolrd MacOS
    needs:
      - hello-world-ubuntu
      - hello-world-windows
    runs-on: macos-latest
    
    steps:
      - name: Print Hello World MacOS
        run: echo 'Hello World rodando no MacOS'
