name: Compress images
on:
  pull_request:
    paths:
      - '**.avif'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
  push:
    branches:
      - master
      - develop
    paths:
      - '**.avif'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    if: |
      github.repository == 'juice-shop/juice-shop' &&
      (github.event_name != 'pull_request' ||
       github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - name: Checkout Branch
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@2a254d926beda392b8c36e1be95252aa3d534405 # main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          ignorePaths: '**/3d_keychain.jpg,**/favorite-hiking-place.png,**/5.png'
          compressOnly: ${{ github.event_name != 'pull_request' }}
      - name: Create Pull Request
        if: |
          github.event_name != 'pull_request' &&
          steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          title: Auto Compress Images
          delete-branch: true
          commit-message: Compress Images
          body: ${{ steps.calibre.outputs.markdown }}
