name: DevSecOps Pipeline - OWASP Juice Shop
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_project:
    name: Setup Node.js
    runs-on: ubuntu-latest
    steps:
      - name: install source code
        uses: actions/checkout@v4
        
      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # require version 22 to run
          
      - name: install Juice Shop lib
        run: npm install --legacy-peer-deps # require to run juice-shop old lib
  sast_semgrep:
    name: Semgrep check
    runs-on: ubuntu-latest
    needs: build_project 
    steps:
      - uses: actions/checkout@v4
      - name: run Semgrep
        uses: returntocorp/semgrep-action@v1
        continue-on-error: true # continue running if semgrep found error
        with:
          config: "p/javascript"

  sast_sonarqube:
    name: SonarQube Cloud check
    runs-on: ubuntu-latest
    needs: build_project 
    steps:
      - uses: actions/checkout@v4
      - name: SonarQube Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
        # need gihub token and sonar token to link sonarqueue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
  sca_snyk:
    name: Snyk check
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - uses: actions/checkout@v4
      - name: Snyk installing and running
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
      - name: lib checking
      # use "|| true" to continue-on-error since juice-shop has a lot of intentional error
        run: snyk test --severity-threshold=high || true 
  dast_zap:
    name: OWASP ZAP (DAST)
    runs-on: ubuntu-latest
    needs: build_project
    # zap need permission to read and write report in github issues
    permissions:
      issues: write
      contents: read
    steps:
      # zap run in real time so the pipeline has to build project and run it
      - uses: actions/checkout@v4 # build project
      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: install lib for Dast
        run: npm install --legacy-peer-deps
      - name: start juice-shop on virture env # run on VM
        run: |
          npm start &
          npx wait-on http://localhost:3000 --timeout 60000
          
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # need github token to link
          target: 'http://localhost:3000'
          fail_action: false 

  quality_gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [sast_semgrep, sast_sonarqube, sca_snyk, dast_zap]
    steps:
      - name: Evaluate and conclusion
        run: |
          echo "Pipeline đang kiểm tra kết quả từ Semgrep, SonarQube và Snyk..."
          echo "Nếu SonarQube hoặc Snyk phát hiện lỗi High/Critical, lệnh này sẽ được cấu hình để đánh rớt (Fail) toàn bộ quy trình."
