name: DevSecOps Pipeline - OWASP Juice Shop
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_project:
    name: Setup Node.js Môi trường
    runs-on: ubuntu-latest
    steps:
      - name: Kéo source code về
        uses: actions/checkout@v4
        
      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' 
          
      - name: Cài đặt thư viện của Juice Shop
        run: npm install --legacy-peer-deps
  sast_semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    needs: build_project 
    steps:
      - uses: actions/checkout@v4
      - name: run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/javascript"

  sast_sonarqube:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    needs: build_project 
    steps:
      - uses: actions/checkout@v4
      - name: SonarQube Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
  sca_snyk:
    name: Snyk
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - uses: actions/checkout@v4
      - name: Snyk installing and running
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
      - name: lib checking
        run: snyk test --severity-threshold=high || true 
  dast_zap:
    name: OWASP ZAP (DAST)
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - uses: actions/checkout@v4
      - name: Cài đặt Node.js cho phân xưởng DAST
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Cài đặt thư viện cho DAST
        run: npm install --legacy-peer-deps
      - name: Khởi động ngầm Juice Shop trên máy ảo
        run: |
          npm start &
          npx wait-on http://localhost:3000 --timeout 60000
          
      - name: Chạy OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:3000'
          fail_action: false 
  quality_gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [sast_semgrep, sast_sonarqube, sca_snyk, dast_zap]
    steps:
      - name: Evaluate and conclusion
        run: |
          echo "Pipeline đang kiểm tra kết quả từ Semgrep, SonarQube và Snyk..."
          echo "Nếu SonarQube hoặc Snyk phát hiện lỗi High/Critical, lệnh này sẽ được cấu hình để đánh rớt (Fail) toàn bộ quy trình."
