name: SAST Pipeline (Semgrep)

on:
  pull_request:
    branches: ["master"] # O Juice Shop usa 'master' como branch principal

jobs:
  security-scan:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"
          generateSarif: "1"
